### ISSUE TITLE
Doesn't print headers, and --data 'undefined' 

### ISSUE THREAD

**Issue by ChristianTucker** [delirius325/axios-curlirize#12]
I was using this as a way to help with generating my documetation, but unfortunately it doesn't generate headers and when data is specified it prints `--data 'undefined'`

**Comment by delirius325** [comment]
Hi @ChristianTucker,

Could you please supply a code sample? I'd like to take a look at your very specific case - there might be something to change in the plugin's code to accommodate scenarios I didn't think about at first.

Thanks,

**Comment by ashishjain3456** [comment]
Hi @delirius325 , 

I also noticed that if the headers are being supplied at POST function they are not added in the curl. for example below code is not adding headers:
`const headers = {
    'Content-Type': 'text/xml',
  };
Axios.post(url, body, { headers })`

but it works fine when we add in default headers like:
`Axios.defaults.headers.common['Content-Type'] = 'text/xml'`

**Comment by delirius325** [comment]
Thanks for the example @ashishjain3456 ! I'll look into it!

**Comment by iamacup** [comment]
@delirius325 my fork will fix the data undefined, and, depending on your research, also fix the other stuff :)

**Comment by delirius325** [comment]
@iamacup Yeah that's why I asked permission to take what you had done 😄 ! I'm currently adding more test cases and fixing some stuff up. New version will be released to NPM very soon!

Cheers,

**Comment by iamacup** [comment]
I didn't even read the issues before I forked so what a happy coincidence :)

Have a great weekend!

**Comment by delirius325** [comment]
New version has been released to NPM, thanks @iamacup !
