### ISSUE TITLE
Should the fancy-log logger be an option

### ISSUE THREAD

**Issue by binggg** [delirius325/axios-curlirize#15]
Should the logger be an option so that user can use their‘s logger ?

**Comment by delirius325** [comment]
Hi @binggg ,

Yes currently implementing a parameter to change the log (which was done by @uyu423, but he never answered my questions in the PR #14). Therefore I'm just gonna apply the code he made for the logger and publish it.

Version 1.2.0 should be out soon implementing your changes as well as this.

Thanks,

**Comment by delirius325** [comment]
Changed the default logger to `console` (https://github.com/delirius325/axios-curlirize/commit/e789b120763c9042105ac1c64b9549d31ddce33c).

Follow the instructions in the README to change to another logger: 
https://github.com/delirius325/axios-curlirize/blob/master/README.md#changing-the-logger
