### ISSUE TITLE
Multiple calls to curlirize will output the curl command multiple times

### ISSUE THREAD

**Issue by lyle-adeptmind** [delirius325/axios-curlirize#29]
Steps to reproduce:

1. In file1.js (choose any filename), import Axios and Curlirize it.  Set up a function to make an Axios request.
2. In file2.js (choose any filename), import Axios again and Curlirize it.  Set up another function to make an Axios request.
3. Run the application.

Actual behaviour: The CURL output from Axios is displayed twice for each request
Expected behaviour: The CURL output is displayed only once (per request) no matter how many times Axios is curlirized.

Thanks!

**Comment by aszpreece** [comment]
Instead of curlirizing the actual axios import, try creating an instance each time and curlirizing that.

**Comment by delirius325** [comment]
The solution @aszpreece suggested is correct.
Closing 😄
