### ISSUE TITLE
Feature request: axios request to curl command only in case of error

### ISSUE THREAD

**Issue by inginheiiro** [delirius325/axios-curlirize#34]
Great module. congrats.
It would be wonderful it could allow (extra feature) only to dump the curl command in case of error.

**Comment by delirius325** [comment]
Hi there,

you could do that by using a custom logger as defined in the first few lines of the `README.md` file.

```javascript
// when initiating your curlirize instance
curlirize(axios, (result, err) => {
  const { command } = result;
  if (err) {
    // use your logger here
  } else {
    // use your logger here
  }
});
```

Now obviously, you would just remove the `else` clause and you'd be good to go.
