### ISSUE TITLE
Documentation doesn't cover some cases

### ISSUE THREAD

**Issue by kenjura** [delirius325/axios-curlirize#35]
The documentation should be updated to explain the "axios" parameter in "curlirize(axios)".

If you are using the syntax below:
`const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});` (copied from axios readme)

Then you would need to invoke curlirize using "curlirize(instance)" after creating the instance. Even invoking it on "axios" before creating the instance doesn't cause the hook to be inherited.

Lost of a bit of time to that gotcha.

**Comment by delirius325** [comment]
Indeed, doing :

```javascript
curlirize(axios)
```

will only "curilirize" the base instance. Any "standalone" instance also needs to be "curlirized".
I will add the use case in the README.
