### ISSUE TITLE
Getting unexpected token on import.

### ISSUE THREAD

**Issue by rajkthapa** [delirius325/axios-curlirize#44]
I am getting the error below

```
import { CurlHelper } from "./lib/CurlHelper.js";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```
  "dependencies": {
    "axios": "^0.18.0",
    "axios-curlirize": "^1.3.5",
.....

Let me know if anything else needed

**Comment by delirius325** [comment]
Aside from using the new native Node modules and linting fixes, there's nothing new in 1.4.0. Please use 1.3.7 if you're experiencing this error.
